/* ===============================
   Travel Radar LK
   Stable Header/Footer System
================================= */

/* ========= BASE PATH (для GitHub Pages) ========= */
function getBasePath() {
    const hostname = window.location.hostname;
    const pathname = window.location.pathname;

    if (hostname.endsWith('.github.io')) {
        const segments = pathname.split('/').filter(Boolean);
        if (segments.length > 0) {
            return '/' + segments[0];
        }
    }

    return '';
}

const BASE = getBasePath();

/* ========= LANGUAGE ========= */
function getCurrentLang() {
    const segments = window.location.pathname.split('/').filter(Boolean);
    const first = segments[0];

    if (['ru', 'ua', 'en'].includes(first)) {
        return first;
    }

    return 'ru';
}

/* ========= EARLY THEME ========= */
(function () {
    const theme = localStorage.getItem('theme') || 'dark';
    document.documentElement.setAttribute('data-theme', theme);
})();

/* ========= LOAD PARTIALS ========= */
/* Версия partials: меняйте вручную при правке header/footer,
   чтобы сбросить кэш у пользователей. Не используем Date.now()/no-store,
   иначе header и footer перекачиваются с сети на каждой навигации. */
const PARTIALS_VERSION = '2026-06-08';

async function loadPartials() {
    try {
        const lang = getCurrentLang();

        const headerPath = `${BASE}/Partials/header-${lang}.html`;
        const footerPath = `${BASE}/Partials/footer-${lang}.html`;

        const headerPlaceholder = document.getElementById('site-header');
        const footerPlaceholder = document.getElementById('site-footer');

        if (!headerPlaceholder || !footerPlaceholder) {
            console.error('❌ Missing header or footer placeholder');
            return;
        }

        const [headerRes, footerRes] = await Promise.all([
            fetch(headerPath + '?v=' + PARTIALS_VERSION),
            fetch(footerPath + '?v=' + PARTIALS_VERSION)
        ]);

        if (!headerRes.ok || !footerRes.ok) {
            console.error('❌ Failed loading partials');
            return;
        }

        headerPlaceholder.innerHTML = await headerRes.text();
        footerPlaceholder.innerHTML = await footerRes.text();

        fixNavigationLinks();
        initLanguageSwitcher();
        initThemeToggle();
        initMobileMenu();
        initActiveNav();

        window.addEventListener('hashchange', initActiveNav);

        loadContentMenu(lang);

    } catch (err) {
        console.error('❌ Partials error:', err);
    }
}

/* ========= CONTENT MENU (3rd partial, like header/footer) ========= */
/* Single source: dev/generator/i18n.mjs (switcher) → Partials/content-menu-<lang>.html
   (generated by build-content-menu.mjs). Injected into the .article-nav-wrap anchor
   that already exists in every article — article files are NOT modified. The inline
   legacy nav inside that anchor stays as a no-JS fallback and is replaced when JS runs.
   Hub pages render the same menu from the same i18n.mjs at build time. */
async function loadContentMenu(lang) {
    const wrap = document.querySelector('.article-nav-wrap');
    if (!wrap) return; // anchor exists only on article pages

    try {
        const res = await fetch(`${BASE}/Partials/content-menu-${lang}.html?v=${PARTIALS_VERSION}`);
        if (!res.ok) return; // keep the legacy fallback if the partial is missing
        wrap.innerHTML = await res.text();
    } catch (err) {
        console.error('❌ Content menu error:', err);
    }
}

/* ========= FIX NAVIGATION ========= */
function fixNavigationLinks() {
    const lang = getCurrentLang();

    // Переписываем ТОЛЬКО header и footer
    document.querySelectorAll('#site-header a, #site-footer a').forEach(link => {
        let href = link.getAttribute('href');
        if (!href) return;

        // Игнорируем внешние ссылки
        if (
            href.startsWith('http') ||
            href.startsWith('mailto:') ||
            href.startsWith('tel:')
        ) return;

        // Якоря (#about)
        if (href.startsWith('#')) {
            link.setAttribute('href', `/${lang}/${href}`);
            return;
        }

        // Убираем старый языковой префикс
        href = href.replace(/^\/(ru|ua|en)\//, '/');

        // Если абсолютный путь
        if (href.startsWith('/')) {
            link.setAttribute('href', `/${lang}${href}`);
            return;
        }

        // Если относительный (content/, egypt/)
        link.setAttribute('href', `/${lang}/${href}`);
    });

    // Логотип всегда ведёт на главную языка
    const brand = document.querySelector('#site-header .brand');
    if (brand) {
        brand.setAttribute('href', `/${lang}/`);
    }
}

/* ========= LANGUAGE SWITCHER ========= */
function initLanguageSwitcher() {
    const currentLang = getCurrentLang();
    const pathname = window.location.pathname;
    const hash = window.location.hash;
    const search = window.location.search;

    const cleanPath = pathname.replace(/^\/(ru|ua|en)/, '');

    document.querySelectorAll('.lang-link').forEach(link => {
        const targetLang = link.dataset.lang;

        const newHref = `/${targetLang}${cleanPath}${search}${hash}`;
        link.setAttribute('href', newHref);

        link.classList.toggle('active', currentLang === targetLang);
    });
}

/* ========= ACTIVE NAV ========= */
function initActiveNav() {
    const pathname = window.location.pathname;
    const hash = window.location.hash;
    const navLinks = document.querySelectorAll('#site-header .nav-link');

    navLinks.forEach(link => {
        link.classList.remove('active');
        link.removeAttribute('aria-current');
    });

    if (pathname.includes('/content')) {
        navLinks.forEach(link => {
            if (link.href.includes('content')) {
                link.classList.add('active');
                link.setAttribute('aria-current', 'page');
            }
        });
        return;
    }

    if (pathname.includes('/about')) {
        navLinks.forEach(link => {
            if (link.href.includes('/about')) {
                link.classList.add('active');
                link.setAttribute('aria-current', 'page');
            }
        });
        return;
    }

    if (hash === '#destinations') {
        navLinks.forEach(link => {
            if (link.href.includes('#destinations')) {
                link.classList.add('active');
                link.setAttribute('aria-current', 'page');
            }
        });
    }
}

/* ========= THEME ========= */
function initThemeToggle() {
    const toggle = document.getElementById('themeToggle');
    if (!toggle) return;

    const currentTheme = document.documentElement.getAttribute('data-theme') || 'dark';
    updateThemeIcon(currentTheme);

    toggle.addEventListener('click', () => {
        const current = document.documentElement.getAttribute('data-theme') || 'dark';
        const newTheme = current === 'dark' ? 'light' : 'dark';

        document.documentElement.setAttribute('data-theme', newTheme);
        localStorage.setItem('theme', newTheme);
        updateThemeIcon(newTheme);
    });
}

function updateThemeIcon(theme) {
    const toggle = document.getElementById('themeToggle');
    if (!toggle) return;

    toggle.textContent = theme === 'dark' ? '☀️' : '🌙';
}

/* ========= MOBILE MENU ========= */
function initMobileMenu() {
    const mobileToggle = document.getElementById('mobileToggle');
    const navMenu = document.getElementById('navMenu');

    if (!mobileToggle || !navMenu) return;

    mobileToggle.addEventListener('click', () => {
        const isActive = navMenu.classList.toggle('active');
        mobileToggle.classList.toggle('active');
        mobileToggle.setAttribute('aria-expanded', isActive);
        document.body.style.overflow = isActive ? 'hidden' : '';
    });

    window.addEventListener('resize', () => {
        if (window.innerWidth > 768) {
            navMenu.classList.remove('active');
            mobileToggle.classList.remove('active');
            document.body.style.overflow = '';
        }
    });
}

/* ========= BACK TO TOP =========
   Small circular button that appears after a noticeable scroll and smoothly
   returns to the top. Site-wide: appended to <body> on every page, independent
   of the partials fetch (works even if header/footer fail to load). Icon-only,
   language-neutral. Styles live in assets/css/base.css (.back-to-top). */
function initBackToTop() {
    if (document.querySelector('.back-to-top')) return; // avoid double init

    const btn = document.createElement('button');
    btn.type = 'button';
    btn.className = 'back-to-top';
    btn.setAttribute('aria-label', 'Back to top');
    btn.innerHTML = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 19V5M5 12l7-7 7 7"/></svg>';
    document.body.appendChild(btn);

    const SHOW_AFTER = 600; // px scrolled before the button appears
    let ticking = false;

    function update() {
        const y = window.pageYOffset || document.documentElement.scrollTop || 0;
        btn.classList.toggle('is-visible', y > SHOW_AFTER);
        ticking = false;
    }

    window.addEventListener('scroll', function () {
        if (!ticking) {
            window.requestAnimationFrame(update);
            ticking = true;
        }
    }, { passive: true });

    btn.addEventListener('click', function () {
        const reduce = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
        window.scrollTo({ top: 0, behavior: reduce ? 'auto' : 'smooth' });
    });

    update(); // set initial state (handles pages loaded already scrolled)
}

/* ========= INIT ========= */
document.addEventListener('DOMContentLoaded', loadPartials);
document.addEventListener('DOMContentLoaded', initBackToTop);
